#!/bin/sh
 
#package name
LC_ALL=C find . -type f -name '*.json' -exec sed -i '' "s/com.stansassets.package-sample/$1/g" {} +
LC_ALL=C find . -type f -name '*.cs' -exec sed -i '' "s/com.stansassets.package-sample/$1/g" {} +
LC_ALL=C find . -type f -name '*.md' -exec sed -i '' "s/com.stansassets.package-sample/$1/g" {} +

#namespace
LC_ALL=C find . -type f -name '*.cs' -exec sed -i '' "s/StansAssets.PackageSample/$2/g" {} +
LC_ALL=C find . -type f -name '*.asmdef' -exec sed -i '' "s/StansAssets.PackageSample/$2/g" {} +

#rename files
find . -type f -name 'StansAssets.PackageSample*' | while read FILE ; do
	regexp="s/StansAssets.PackageSample/$2/";
    newfile="$(echo ${FILE} | sed -e ${regexp})";
    mv "${FILE}" "${newfile}";
done 

mv 'com.stansassets.package-sample' "${1}";

PROJECT_NAME=$(echo "$2" | sed 's/^.*\.//')
mv 'PackageSampleProject' "${PROJECT_NAME}Project";
find . -type f -name 'com.stansassets.package-sample*' | while read FILE ; do
	regexp="s/com.stansassets.package-sample/$1/";
    newfile="$(echo ${FILE} | sed -e ${regexp})";
    mv "${FILE}" "${newfile}";
done 


echo "package name: $1"
echo "package namespace: $2"
